services:
  daily-quote:
    image: ghcr.io/rondevhub/daily-quote:latest
    container_name: daily_quote_app
    ports:
      - "8080:80"
    environment:
      - APP_LINK_IMPRESSUM=true #Soll das Impressum auf der Seite erscheinen? true = ja, false = nein
      - APP_OWNER_NAME=[Dein Name / Betreibername]
      - APP_OWNER_STREET=[Deine Straße und Hausnummer]
      - APP_OWNER_CITY=[Deine PLZ und Ort]
      # Alternativ kannst du auch unter https://mail-shield.net/ einen Link für Deine E-Mail generieren und diesen Link hier eintragen
      - APP_OWNER_EMAIL=[Deine E-Mail-Adresse]
    restart: unless-stopped