services:
  daily-quote:
    image: ghcr.io/rondevhub/daily-quote:latest
    container_name: daily_quote_app
    ports:
      - "8080:80"
    environment:
      - APP_OWNER_NAME=${APP_OWNER_NAME:-[Dein Name / Betreibername]}
      - APP_OWNER_STREET=${APP_OWNER_STREET:-[Deine Straße und Hausnummer]}
      - APP_OWNER_CITY=${APP_OWNER_CITY:-[Deine PLZ und Ort]}
      - APP_OWNER_EMAIL=${APP_OWNER_EMAIL:-[Deine E-Mail-Adresse]}
    restart: unless-stopped